/*
 * @Author: cola
 * @Date: 2022-10-31 11:08:30
 * @LastEditors: cola
 * @Description:
 */
// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    DemoPage: typeof import('./src/views/demo/DemoPage.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ErrorPage: typeof import('./src/views/error/ErrorPage.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomePage: typeof import('./src/views/home/HomePage.vue')['default']
    LayoutPage: typeof import('./src/layout/LayoutPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TreeGroup: typeof import('./src/components/GlobalTree/components/TreeGroup.vue')['default']
    TreeItem: typeof import('./src/components/GlobalTree/components/TreeItem.vue')['default']
  }
}
