// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    GlobalBreadcrumb: typeof import('./src/components/GlobalBreadcrumb/GlobalBreadcrumb.vue')['default']
    GlobalIcon: typeof import('./src/components/GlobalIcon/GlobalIcon.vue')['default']
    GlobalTree: typeof import('./src/components/GlobalTree/GlobalTree.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ICustomUser: typeof import('~icons/custom/user')['default']
    IMdiAccountCircle: typeof import('~icons/mdi/account-circle')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TreeGroup: typeof import('./src/components/GlobalTree/components/TreeGroup.vue')['default']
    TreeItem: typeof import('./src/components/GlobalTree/components/TreeItem.vue')['default']
  }
}
